module.exports = {
	extends: ['eslint:recommended', 'airbnb-base'],
	plugins: ['@babel', 'import'],
	parser: '@babel/eslint-parser',
	parserOptions: {
		ecmaVersion: 12,
		sourceType: 'module',
	},
	rules: {
		'@babel/new-cap': ['error'],
		'@babel/no-invalid-this': ['error'],
		'@babel/no-unused-expressions': ['error'],
		'@babel/object-curly-spacing': ['error', 'always'],
		'@babel/semi': ['error', 'always'],
		'array-bracket-spacing': ['error', 'never'],
		'arrow-body-style': ['off'],
		'arrow-parens': ['error', 'always'],
		'camelcase': ['error', { properties: 'always' }],
		'comma-dangle': ['error', 'always-multiline'],
		'import/prefer-default-export': ['off'],
		'indent': ['error', 'tab'],
		'max-len': ['error', { code: 150 }],
		'new-cap': ['off'],
		'no-bitwise': ['off'],
		'no-console': ['warn', { allow: ['error', 'warn'] }],
		'no-invalid-this': ['off'],
		'no-plusplus': ['off'],
		'no-restricted-syntax': ['off'],
		'no-tabs': ['error', { allowIndentationTabs: true }],
		'no-underscore-dangle': ['off'],
		'no-unused-expressions': ['off'],
		'object-curly-newline': ['error', { multiline: true, consistent: true }],
		'object-curly-spacing': ['off'],
		'prefer-destructuring': ['off'],
		'quote-props': ['error', 'consistent'],
		'quotes': ['error', 'single'],
		'semi': ['off'],
		'wrap-iife': ['error', 'inside'],
	},
};
